ArtGallery/Controllers/AdminController.cs
using ArtGallery.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArtGallery.Controllers
{
    [Route("[controller]/[action]")]
    public class AdminController : Controller
    {
        private readonly RepositoryContext db;

        public AdminController(RepositoryContext _db)
        {
            db = _db;
        }

        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Admin admin)
        {
            if (ModelState.IsValid)
            {
                await db.Admins.AddAsync(admin);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(admin);
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Admin> admins = await db.Admins.ToListAsync();
            return View(admins);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            
            var admin = await db.Admins.FindAsync(id);
            if (admin == null)
            {
                return NotFound();
            }
            return View(admin);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Admins.Update(admin);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(admin);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var admin = db.Admins.Find(id);
            if (admin == null)
            {
                return NotFound();
            }
            db.Admins.Remove(admin);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

ArtGallery/Controllers/ArtMovementController.cs
using ArtGallery.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArtGallery.Controllers
{
    [Route("[controller]/[action]")]
    public class ArtMovementController : Controller
    {
        private readonly RepositoryContext db;

        public ArtMovementController(RepositoryContext _db)
        {
            db = _db;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ArtMovement art)
        {
            if (ModelState.IsValid)
            {
                await db.ArtMovements.AddAsync(art);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(art);
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<ArtMovement> arts = await db.ArtMovements.ToListAsync();
            return View(arts);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var art = await db.ArtMovements.FindAsync(id);
            if (art == null)
            {
                return NotFound();
            }
            return View(art);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ArtMovement art)
        {
            if (ModelState.IsValid)
            {
                db.ArtMovements.Update(art);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(art);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var art = db.ArtMovements.Find(id);
            if (art == null)
            {
                return NotFound();
            }
            db.ArtMovements.Remove(art);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

ArtGallery/Controllers/PainterController.cs
using ArtGallery.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArtGallery.Controllers
{
    [Route("[controller]/[action]")]
    public class PainterController : Controller
    {
        private readonly RepositoryContext db;

        public PainterController(RepositoryContext _db)
        {
            db = _db;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Painter p)
        {
            if (ModelState.IsValid)
            {
                await db.Painters.AddAsync(p);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(p);
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Painter> ps = await db.Painters.ToListAsync();
            return View(ps);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var p = await db.Painters.FindAsync(id);
            if (p == null)
            {
                return NotFound();
            }
            return View(p);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Painter p)
        {
            if (ModelState.IsValid)
            {
                db.Painters.Update(p);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(p);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var p = db.Painters.Find(id);
            if (p == null)
            {
                return NotFound();
            }
            db.Painters.Remove(p);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

ArtGallery/Controllers/PaintingController.cs
using ArtGallery.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace ArtGallery.Controllers
{
    [Route("[controller]/[action]")]

    public class PaintingController : Controller
    {
        private readonly RepositoryContext db;

        public PaintingController(RepositoryContext _db)
        {
            db = _db;
        }

        [HttpGet]
        public IActionResult Create()
        {
            var painters = db.Painters.ToList();
            ViewBag.Painters = new SelectList(painters, "Id", "LastName");
            var arts = db.ArtMovements.ToList();
            ViewBag.ArtMovements = new MultiSelectList(arts, "Id", "Name");//doesn't work - can't write multiple values in List<ArtMovement>
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Painting p)
        {
            if (ModelState.IsValid)
            {
                await db.Paintings.AddAsync(p);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(p);
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Painting> ps = await db.Paintings.ToListAsync();
            return View(ps);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var p = await db.Paintings.FindAsync(id);
            if (p == null)
            {
                return NotFound();
            }
            var painters = db.Painters.ToList();
            ViewBag.Painters = new SelectList(painters, "Id", "LastName");
            var arts = db.ArtMovements.ToList();
            ViewBag.ArtMovements = new MultiSelectList(arts, "Id", "Name");//doesn't work - can't write multiple values in List<ArtMovement>

            return View(p);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Painting p)
        {
            if (ModelState.IsValid)
            {
                db.Paintings.Update(p);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(p);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var p = db.Paintings.Find(id);
            if (p == null)
            {
                return NotFound();
            }
            db.Paintings.Remove(p);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

ArtGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArtGallery</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Painter" asp-action="Index">Художники админ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Админы админ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="ArtMovement">Направления админ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Painting" asp-action="Index">Картины админ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Painters">Художники</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Paintings">Картины</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ArtMovements">Направления</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ArtGallery - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>